### ISSUE TITLE
configurability documentation

### ISSUE THREAD

**Issue by sf8193** [presubmit/ai-reviewer#37]
you mention it can be configured with specific rules etc, but i see no documentation on that in the readme

**Comment by bstanga** [comment]
Yes, will add that. Meanwhile you can have custom style guide rules by setting `env.STYLE_GUIDE_RULES` to your custom rules.

It's being used [here](https://github.com/presubmit/ai-reviewer/blob/19a526f8497b79bea5d24842000178115ad196c3/src/prompts.ts#L193).

**Comment by kingychiu** [comment]
For your reference, we are using this to inject the rule to the reviewer:

```
  ai_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get style guide rules from file
        id: style-guide
        run: |
          CONTENT=$(cat .github/copilot-instructions.md)
          echo "styleGuideRules<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
      - uses: presubmit/ai-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: "your_choice"
        with:
          style_guide_rules: ${{ steps.style-guide.outputs.styleGuideRules }}
```

- the checkout fetches the code 
- the next `Get style guide rules from file` output the the content of the file `.github/copilot-instructions.md` to the step output  `steps.style-guide.outputs.styleGuideRules`
- then passing into the `style_guide_rules` input of presubmit/ai-reviewer@latest
